### PR TITLE
Fix `node.pruning_*` unit tests

### LINKED ISSUE #3641: Unit test `node.pruning_age` intermittently failing
Disabled in https://github.com/nanocurrency/nano-node/pull/3629

CI run in which it failed: [here](https://github.com/nanocurrency/nano-node/runs/4569228026?check_suite_focus=true#step:5:1180)

### PR DESCRIPTION
**Pull request by theohax**
One more batch of fixes, put them in the same PR due to the tests being fairly similar to one another.

One of them (`node.pruning_age`) just very recently was disabled in #3629, so linking the respective issue (#3641) to this PR.

### CODE REVIEW

File: nano/core_test/node.cpp [hunk 1]
```diff
@@ -4300,161 +4300,176 @@ TEST (rep_crawler, local)
...
 	// Pruning with max age 0
-	node1.config.max_pruning_age = std::chrono::seconds (0);
+	node1.config.max_pruning_age = std::chrono::seconds{ 0 };
 	node1.ledger_pruning (1, true, false);
 	ASSERT_EQ (1, node1.ledger.cache.pruned_count);
 	ASSERT_EQ (3, node1.ledger.cache.block_count);
+
 	ASSERT_TRUE (node1.ledger.block_or_pruned_exists (nano::dev::genesis->hash ()));
-	ASSERT_TRUE (node1.ledger.block_or_pruned_exists (send1->hash ())); // true for pruned
+	ASSERT_TRUE (node1.ledger.block_or_pruned_exists (send1->hash ()));
```
Comment (thsfs) [inline nano/core_test/node.cpp:4417]: I wouldn't remove this comment as it is there to facilitate debugging. If you have more info to add about the tests please do so.

File: nano/core_test/node.cpp [hunk 2]
```diff
@@ -4300,161 +4300,176 @@ TEST (rep_crawler, local)
 
 TEST (node, pruning_automatic)
```
Comment (dsiganos) [inline nano/core_test/node.cpp:4306]: Can we add a comment describing the intention of this unit test?

**Review by dsiganos — DISMISSED** [review]

File: nano/core_test/node.cpp (hunk 2 above)
Comment (theohax) [reply nano/core_test/node.cpp:4306]: Will do, thanks

File: nano/core_test/node.cpp (hunk 1 above)
Comment (theohax) [reply nano/core_test/node.cpp:4417]: I did add some relevant comments at the beginning of the tests.

**Review by dsiganos — APPROVED** [review]
