### PR TITLE
Fix and re-enable unit test rpc.wallet_history

### LINKED ISSUE #3514: Unit test `rpc.wallet_history` intermittently failing
Disabled in https://github.com/nanocurrency/nano-node/pull/3512/commits/e1d0a51253d19fa725fb30fc84880c89ddc50527

### PR DESCRIPTION
**Pull request by dsiganos**
It appears that the problme was that a timestamp was checked for exactness instead of chacking for a time range.

fixes #3514

### CODE REVIEW

**Review by clemahieu — DISMISSED** [review]

File: nano/rpc_test/rpc.cpp [hunk 1]
```diff
@@ -5613,6 +5608,7 @@ TEST (rpc, DISABLED_wallet_history)
 	request.put ("action", "wallet_history");
 	request.put ("wallet", node->wallets.items.begin ()->first.to_string ());
 	auto response (wait_response (system, rpc_ctx, request));
+	boost::property_tree::write_json (std::cout, response);
```
Comment (pwojcikdev) [inline nano/rpc_test/rpc.cpp]: Having logs from tests is great, but please only write to stdout if logging is enabled.

Comment (dsiganos) [reply nano/rpc_test/rpc.cpp]: No, was not meant to  be there. I will remove it.

**Comment by dsiganos** [comment]
Looks like I messed up the last tw check, I will fix them.
