### PR TITLE
Investigate and fix some of the disabled unit tests

### LINKED ISSUE #3522: Unit test `active_transactions.confirm_active` intermittently failing
Not yet disabled

### LINKED ISSUE #3528: Unit test `election.quorum_minimum_update_weight_before_quorum_checks` intermittently failing
Disabled in https://github.com/nanocurrency/nano-node/pull/3526/commits/7bf2c426fb69851c7079c29d6ba8551723c7f32a

### LINKED ISSUE #3557: Unit test `node.vote_by_hash_republish` intermittently failing
Disabled in https://github.com/nanocurrency/nano-node/pull/3556

CI run in which it failed: [here](https://github.com/nanocurrency/nano-node/runs/4278407269?check_suite_focus=true#step:6:1144)

### LINKED ISSUE #3605: Unit test `active_transactions.inactive_votes_cache_fork` intermittently failing
Disabled in https://github.com/nanocurrency/nano-node/pull/3604

CI run in which it failed: [here](https://github.com/nanocurrency/nano-node/runs/4512404171?check_suite_focus=true#step:5:1034)

### PR DESCRIPTION
**Pull request by theohax**
This PR enables back a bunch of tests that we have been disabling due to their intermittent failures.

Once the PR is ready for merging, I'll update the relevant GitHub issues as well.

### CODE REVIEW

File: nano/core_test/active_transactions.cpp [hunk 1]
```diff
@@ -11,60 +11,62 @@ using namespace std::chrono_literals;
...
-	node1.history.erase (send->root ()); // Have to erase existing non-final vote for final vote generation (at runtime it should be replaced with automatically generated final vote from election)
+
+	// Vote was inserted (+ not_an_account)
+	ASSERT_TIMELY (5s, election->votes ().size () == 2);
+	// Cannot be confirmed without final vote
+	ASSERT_FALSE (election->confirmed ());
+
+	// TODO: investigate
+	//
+	// auto const confirm_req_count = election->confirmation_request_count.load();
```
Comment (theohax) [inline nano/core_test/active_transactions.cpp]: @clemahieu -- need a bit of help with this one. It fails randomly, but definitely reproducible. I'd actually say it fails more than it passes. Any thoughts why the confirmation requests wouldn't be seen?

File: nano/core_test/active_transactions.cpp [hunk 2]
```diff
@@ -11,60 +11,62 @@ using namespace std::chrono_literals;
...
-	auto & node2 = *system.add_node (node_config2, node_flags2);
+	nano::system system{};
 	system.deadline_set (5s);
-	// Let node2 know about the block
-	while (node2.active.empty ())
-	{
-		node1.network.flood_block (send, nano::buffer_drop_policy::no_limiter_drop);
-		ASSERT_NO_ERROR (system.poll ());
-	}
-	// Save election to check request count afterwards
```
Comment (thsfs) [inline nano/core_test/active_transactions.cpp:44]: We are losing this comment and the past two ones. Could you document the new code?

Comment (theohax) [reply nano/core_test/active_transactions.cpp:44]: These lines specifically should need no comments at all, they're a standard pattern we're using to check that the block has been processed and election started. But yeah, I'll do add some docs here and there where they would help more.

**Comment by theohax** [comment]
Updated (and linked to this PR) the issues that this PR addresses:

- #3522 
- #3528
- #3605
- #3608
- #3557

**Comment by theohax** [comment]
@reviewers -- now ready for final review.

**Review by dsiganos — APPROVED** [review]

**Comment by theohax** [comment]
Couple tests failed in the CI:

- `election_scheduler.no_vacancy` -- this one is already on my to-fix list 
- `confirmation_height.election_winner_details_clearing` -- PR already open about it -- #3688 
- `timer.measure_and_compare` -- probably an odd (and very rare - I've never seen it before) failure? Ignoring it unless further repeats

Merging this
